### ISSUE TITLE
UI flow for figure generation is confusing

### ISSUE THREAD

**Issue by simonjamespratt** [simonjamespratt/Montage#42]
See basecamp and other issues here. This is probably a project. But it is quite important as it's very hard to follow and if you do things in the wrong order you will get results you don't expect. Knowing this also makes you doubt the result as a user.

Message in Basecamp that this originally came from: https://3.basecamp.com/4385741/buckets/19829197/messages/3588450260

### TODO:
- [x] Test output of new flow
- [x] State pattern for stages of UI flow?
- [x] Reinstate UI error display
- [x] Static method for making duration protocols?
- Viewports - not done
- [x] Tighten up styles/UI
- [x] Move experiments with ValueTrees and CachedValue for non-primitive types into a gist
- [x] Disable "add figure" button on Figures page when not enough particles
- [x] Delete old files

### Original idea for changing viewport, not implemented:

FigureGenerator should have a scrollbar/viewport - no sub-components
should have them. Sub components that currently have them:
* RatioProtocolController
* PrecisionProtocolController
* GroupedRepetitionProtocolController
* MultiplesProtocolController
* PrescribedProtocolController

So for clarity, all those sub components still have them and FigureGenerator still does not have one!

**Comment by simonjamespratt** [comment]
Viewports were not altered in the end. Decided it was too much of a time sink to sort it out. For following reasons:
* Adding a viewport around the `...Stage` pointers was tricky (pointers and lifecycles of these components)
* Removing viewports around the `NumericCollectionEditor`s means that you would need to calculate the whole of the content you added inside the viewed component which is hard to know

**Comment by simonjamespratt** [comment]
Gist for experiments with ValueTree, CachedValue and non-primitive types: https://gist.github.com/simonjamespratt/cc232886098ff6c6997cdaa9dc36bef5
